name: Fake Open Source event saving

on:
  issues:
    types:
      - opened

jobs:
  store:
    runs-on: ubuntu-latest
    if: "contains(github.event.issue.labels.*.name, 'event')"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - id: issue-parser
        uses: stefanbuck/github-issue-parser@v3
        with:
          template-path: ".github/ISSUE_TEMPLATE/Fake-Open-Source-event.yml"

      - name: Save issue to Markdown & YAML
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_LINK: ${{ github.event.issue.html_url }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          EVENT_TAGS: ${{ steps.issue-parser.outputs.issueparser_tags }}
          EVENT_START_TIME: ${{ steps.issue-parser.outputs.issueparser_start_time }}
          EVENT_END_TIME: ${{ steps.issue-parser.outputs.issueparser_end_time }}
          EVENT_LOCATION: ${{ steps.issue-parser.outputs.issueparser_location }}
          EVENT_WHISTLEBLOWER: ${{ github.event.issue.user.html_url }}
          EVENT_HYPOCRITE: ${{ steps.issue-parser.outputs.issueparser_hypocrite }}
          EVENT_MONEY: ${{ steps.issue-parser.outputs.issueparser_money }}
        run: |
          bash .github/scripts/save-event.sh

      - uses: peter-evans/create-pull-request@v8
        with:
          title: "docs(event): add data of ${{ github.event.issue.title }}"
          body: "fix #${{ github.event.issue.number }}"
