name: Activity submission

on:
  issues:
    types:
      - opened

jobs:
  store:
    runs-on: ubuntu-latest
    if: "contains(github.event.issue.labels.*.name, 'activity')"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - id: issue-parser
        uses: stefanbuck/github-issue-parser@v3
        with:
          template-path: ".github/ISSUE_TEMPLATE/activity.yml"

      - name: Save activity to YAML
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_LINK: ${{ github.event.issue.html_url }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ACTIVITY_TYPE: ${{ steps.issue-parser.outputs.issueparser_type }}
          ACTIVITY_DESCRIPTION: ${{ steps.issue-parser.outputs.issueparser_description }}
          ACTIVITY_TAGS: ${{ steps.issue-parser.outputs.issueparser_tags }}
          ACTIVITY_ID: ${{ steps.issue-parser.outputs.issueparser_id }}
          ACTIVITY_LINK: ${{ steps.issue-parser.outputs.issueparser_link }}
          ACTIVITY_START_TIME: ${{ steps.issue-parser.outputs.issueparser_start_time }}
          ACTIVITY_END_TIME: ${{ steps.issue-parser.outputs.issueparser_end_time }}
          ACTIVITY_TIMELINE: ${{ steps.issue-parser.outputs.issueparser_timeline }}
          ACTIVITY_TIMEZONE: ${{ steps.issue-parser.outputs.issueparser_timezone }}
          ACTIVITY_PLACE: ${{ steps.issue-parser.outputs.issueparser_place }}
        run: |
          bash .github/scripts/save-event.sh

      - uses: peter-evans/create-pull-request@v8
        with:
          title: "data(activity): add ${{ github.event.issue.title }}"
          body: "fix #${{ github.event.issue.number }}"
